# .github/configs/label-commenter-config.yml

labels:
  - name: 'active'
    labeled:
      issue:
        body: |
          **🎉 恭喜，友链添加成功！**

          稍后片刻刷新网页就可以看到您的链接。

          > 如果您的站点信息发生了变动，请直接修改这个 issue 的内容。

  - name: 'suspend'
    labeled:
      issue:
        body: |
          **👋 请及时添加本站友链**

          距离成功只剩一步之遥了，请把本站添加到您的友链中，然后再下方评论告知。

  - name: '404'
    labeled:
      issue:
        body: |
          **⚠️ 抱歉，您的网站打不开，现已下架/拒绝申请。**

          如果您确认可以打开，请在下方评论告知，我们会在人工审核通过后恢复上架。

  - name: 'not-meeting-requirements'
    labeled:
      issue:
        body: |
          **⚠️ 抱歉，您的网站缺少必要信息/不符合要求，现已下架/拒绝申请。**

          请确认您填写了 issue 模板中除了 `screenshot` 外的所有内容，并确保遵循了 [友链页](https://www.cubik65536.top/friends/#%E5%85%B3%E4%BA%8E%E5%8F%8B%E9%93%BE) 上的所有要求。

          如果您确认符合要求，请在下方评论告知，我们会在人工审核通过后恢复上架。
