# 网络请求设置
request:
  timeout: 10 # 超时设置
  ssl: false # ssl设置

# 要抓取的 issues 配置
issues:
  repo: Cubik65536/friends-api # 仓库持有者/仓库名（改成自己的）
  label: active # 筛选具有 active 标签的 issue ，取消此项则会提取所有 open 状态的 issue
  groups: ["friends", "frequently-visited", "developers", "github-friends"] # 填写用来分组的label名称。留空则所有被抓取的issue输出至data.json，否则按照输出与组名同名的json文件
  sort: # updated-desc # 排序，按最近更新，取消此项则按创建时间排序
